apiVersion: v1
kind: Pod
metadata:
  name: script-runner
  labels:
    app: script-runner
spec:
  containers:
    - name: script-runner
      image: ubuntu:latest
      command:
        - /bin/sh
        - -c
        - |
          echo "running below scripts"
          apt update;
          apt install postgresql-client curl wget -y;
          /bin/sleep 3650d;
      imagePullPolicy: IfNotPresent
  restartPolicy: Always